import type { Item, Product, Project } from "./types";
import { shortlistProducts } from "./shortlist";

const now = "2026-08-15T14:30:00.000Z";
const price = (amount: number) => ({
  amount,
  currency: "USD" as const,
  observedAt: now,
  confirmed: true,
});
const evidence = {
  source: "demo_fixture" as const,
  confidence: 1,
  confirmedByUser: true,
};

const coreDemoProducts: Product[] = [
  {
    id: "prod-desk-wide",
    name: "Northline Study Desk",
    store: "Campus Home",
    sourceURL: "https://example.com/northline-desk",
    category: "desk",
    variant: "60 in / oak",
    dimensions: { width: 1.52, depth: 0.76, height: 0.76 },
    price: price(21900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    alternativeGroupId: "desk-compact",
    tags: ["workspace"],
  },
  {
    id: "prod-desk-compact",
    name: "Milo Compact Desk",
    store: "Room & Boardwalk",
    sourceURL: "https://example.com/milo-desk",
    category: "desk",
    variant: "43 in / birch",
    dimensions: { width: 1.09, depth: 0.54, height: 0.75 },
    price: price(13900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    alternativeGroupId: "desk-compact",
    tags: ["workspace"],
  },
  {
    id: "prod-chair",
    name: "Loop Task Chair",
    store: "Campus Home",
    sourceURL: "https://example.com/loop-chair",
    category: "chair",
    variant: "sage",
    dimensions: { width: 0.62, depth: 0.62, height: 0.91 },
    price: price(8900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    tags: ["seating", "workspace"],
  },
  {
    id: "prod-micro-jay",
    name: "QuickHeat 0.7 cu ft Microwave",
    store: "Target",
    sourceURL: "https://example.com/quickheat-microwave",
    category: "microwave",
    variant: "black",
    dimensions: { width: 0.52, depth: 0.4, height: 0.31 },
    price: price(11900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    tags: ["shared-cooking", "high-wattage"],
  },
  {
    id: "prod-micro-maya",
    name: "DormWave Compact Microwave",
    store: "Best Buy",
    sourceURL: "https://example.com/dormwave-microwave",
    category: "microwave",
    variant: "white",
    dimensions: { width: 0.48, depth: 0.38, height: 0.29 },
    price: price(9900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    tags: ["shared-cooking"],
  },
  {
    id: "prod-heater",
    name: "CozyCoil Mini Heater",
    store: "Campus Home",
    sourceURL: "https://example.com/cozycoil-heater",
    category: "heater",
    variant: "cream",
    dimensions: { width: 0.3, depth: 0.2, height: 0.38 },
    price: price(6900),
    fieldEvidence: { dimensions: evidence, price: evidence },
    tags: ["open-coil", "heating"],
  },
  {
    id: "prod-shelf",
    name: "Maya’s Cube Shelf",
    store: "Owned item",
    sourceURL: null,
    category: "storage",
    variant: "white",
    dimensions: { width: 0.76, depth: 0.3, height: 0.76 },
    price: null,
    fieldEvidence: { dimensions: evidence },
    tags: ["storage"],
  },
  {
    id: "prod-dresser",
    name: "Provided Dresser",
    store: "Residence hall",
    sourceURL: null,
    category: "storage",
    variant: "maple",
    dimensions: { width: 0.91, depth: 0.51, height: 0.81 },
    price: null,
    fieldEvidence: { dimensions: evidence },
    tags: ["storage", "provided"],
  },
];

export const demoProducts: Product[] = [...coreDemoProducts, ...shortlistProducts];

export const demoItems: Item[] = [
  {
    id: "item-desk",
    productId: "prod-desk-wide",
    ownerId: "person-jay",
    acquisitionStatus: "buying",
    purchaseStatus: "in_cart",
    quantity: 1,
    essentiality: "essential",
    needsServed: ["workspace"],
    transform: { position: { x: 3.28, y: 2.38 }, rotationZ: 0 },
    placementType: "floor",
  },
  {
    id: "item-chair",
    productId: "prod-chair",
    ownerId: "person-jay",
    acquisitionStatus: "buying",
    purchaseStatus: "in_cart",
    quantity: 1,
    essentiality: "essential",
    needsServed: ["workspace", "seating"],
    transform: { position: { x: 2.48, y: 2.34 }, rotationZ: 0 },
    placementType: "floor",
  },
  {
    id: "item-micro-jay",
    productId: "prod-micro-jay",
    ownerId: "person-jay",
    acquisitionStatus: "buying",
    purchaseStatus: "in_cart",
    quantity: 1,
    essentiality: "optional",
    needsServed: ["shared-cooking"],
    transform: null,
    placementType: "floor",
  },
  {
    id: "item-micro-maya",
    productId: "prod-micro-maya",
    ownerId: "person-maya",
    acquisitionStatus: "planned",
    purchaseStatus: "in_cart",
    quantity: 1,
    essentiality: "optional",
    needsServed: ["shared-cooking"],
    transform: null,
    placementType: "floor",
  },
  {
    id: "item-heater",
    productId: "prod-heater",
    ownerId: "person-jay",
    acquisitionStatus: "buying",
    purchaseStatus: "in_cart",
    quantity: 1,
    essentiality: "optional",
    needsServed: ["warmth"],
    transform: { position: { x: 1.9, y: 0.55 }, rotationZ: 0 },
    placementType: "floor",
  },
  {
    id: "item-shelf",
    productId: "prod-shelf",
    ownerId: "person-maya",
    acquisitionStatus: "owned",
    purchaseStatus: "not_purchasing",
    quantity: 1,
    essentiality: "essential",
    needsServed: ["storage"],
    transform: { position: { x: 0.58, y: 0.62 }, rotationZ: 0 },
    placementType: "floor",
  },
  {
    id: "item-dresser",
    productId: "prod-dresser",
    ownerId: "person-maya",
    acquisitionStatus: "owned",
    purchaseStatus: "not_purchasing",
    quantity: 1,
    essentiality: "essential",
    needsServed: ["storage"],
    transform: { position: { x: 3.08, y: 0.42 }, rotationZ: 0 },
    placementType: "floor",
    locked: true,
  },
];

export function createDemoProject(): Project {
  return {
    schemaVersion: 1,
    id: "project-demo",
    name: "Maple Hall · 214",
    roomType: "Shared dorm",
    ownerId: "person-jay",
    people: [
      { id: "person-jay", name: "Jay", color: "#6e6363" },
      { id: "person-maya", name: "Maya", color: "#5f6aa5" },
    ],
    room: {
      id: "room-demo",
      width: 3.66,
      length: 3.05,
      height: 2.44,
      dimensionEvidence: {
        width: { ...evidence, source: "imported_plan" },
        length: { ...evidence, source: "user_confirmed" },
        height: { ...evidence, source: "user_confirmed" },
      },
      mediaAssets: [
        {
          id: "media-demo",
          name: "move-in walkthrough · frame 03",
          type: "image",
          dataUrl: "/demo-room.svg",
          privacy: "private",
          size: 182400,
        },
      ],
      features: [
        {
          id: "door-entry",
          name: "Entry door",
          kind: "door",
          position: { x: 0.46, y: 0.04 },
          width: 0.91,
          depth: 0.08,
          height: 2.03,
          confirmed: true,
        },
        {
          id: "window-north",
          name: "North window",
          kind: "window",
          position: { x: 2.75, y: 3.01 },
          width: 1.2,
          depth: 0.08,
          height: 1.1,
          confirmed: false,
        },
      ],
      clearanceZones: [
        {
          id: "clear-door-entry",
          name: "Entry door swing",
          position: { x: 0.48, y: 0.48 },
          width: 0.96,
          depth: 0.96,
          source: "user_confirmed",
          confirmed: true,
        },
      ],
      geometryVersion: 1,
      reconstructionStatus: "reviewed",
      palette: [
        { id: "swatch-wall", hex: "#e7dfd0", label: "warm wall", source: "walkthrough · likely wall", pinned: true },
        { id: "swatch-floor", hex: "#a77f59", label: "maple floor", source: "walkthrough · likely floor", pinned: false },
        { id: "swatch-sage", hex: "#7f9186", label: "sage accent", source: "walkthrough · furnishing", pinned: false },
      ],
    },
    products: structuredClone(demoProducts),
    items: structuredClone(demoItems),
    // $400 keeps the cart over budget after the rule/duplicate fixes, so Better Cart demonstrates a substitution.
    budgetAmount: 40000,
    budgetCurrency: "USD",
    priorities: ["Stay under budget", "Keep a clear entry", "Preserve workspace"],
    needs: ["workspace", "seating", "storage"],
    rules: [
      {
        id: "rule-open-coil",
        label: "Maple Hall appliance policy",
        text: "Open-coil heating appliances are not permitted in student rooms.",
        sourceURL: null,
        sourceType: "user_note",
        verificationStatus: "confirmed",
        prohibitedCategories: [],
        prohibitedTags: ["open-coil"],
        dismissed: false,
      },
    ],
    duplicateResolutions: {},
    proposal: null,
    cartVersion: 1,
    createdAt: now,
    updatedAt: now,
  };
}

export function createBlankProject(name = "Untitled room"): Project {
  const project = createDemoProject();
  return {
    ...project,
    id: `project-${crypto.randomUUID()}`,
    name,
    roomType: "Bedroom",
    room: {
      ...project.room,
      id: `room-${crypto.randomUUID()}`,
      width: 3,
      length: 3.4,
      height: 2.4,
      reconstructionStatus: "manual",
      mediaAssets: [],
      features: [],
      clearanceZones: [],
      palette: [],
      geometryVersion: 1,
    },
    products: structuredClone(shortlistProducts),
    items: [],
    budgetAmount: 50000,
    priorities: ["Stay under budget"],
    needs: [],
    rules: [],
    duplicateResolutions: {},
    proposal: null,
    cartVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
